[package]
name = "console-mermaid"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
indexmap = "2.2.6"
log = "0.4.21"
regex = "1.10.4"
unicode-width = "0.1.11"
